apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-inferenceservices-binding
  namespace: ${NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: pipeline-runner-pipelines-definition
    namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: create-inferenceservices
  apiGroup: rbac.authorization.k8s.io